brew cask install alfred
brew cask install witch
brew cask install rightzoom
brew cask install google-chrome 
brew cask install iterm2
brew cask install sublime-text
brew cask install typora
brew cask install sogouinput
brew cask install elmedia-player
brew cask install appcleaner
